version: 2

jobs:
  build:
    working_directory: ~/babel-plugin-css-modules-transform
    docker:
      - image: circleci/node:10.12.0
    steps:
      - checkout
      - restore_cache:
          key: yarndeps-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Installing javascript dependencies
          command: yarn install --cache-folder ~/.yarn-cache
      - save_cache:
          key: yarndeps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.yarn-cache
      - run:
          name: Linting the source code
          command: yarn lint
      - run:
          name: Testing the source code
          command: |
            yarn test
            # test with babel 7
            ./install-babel-7.sh
            BABEL_7=1 yarn test
